apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kusama-otv-backend
  namespace: argocd
# finalizers:
# - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kusama
  project: 1kv-backend
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true 
  source:
    repoURL: https://w3f.github.io/helm-charts/
    chart: otv-backend
    targetRevision: v2.8.31
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            image:
              tag: "v2.8.31"
            environment: "production"
            dataPath: "/data"
            backendPort: 3300
            domain: "test.domain"

            resources:
              limits:
                cpu: 3500m
                memory: 9Gi
              requests:
                cpu: 700m
                memory: 3Gi

            secret: "aa"

            config: |
              {
                "global": {
                  "dryRun": false,
                  "networkPrefix": 2,
                  "test": false,
                  "retroactive": false,
                  "historicalNominations": false,
                  "apiEndpoints": [
                    "wss://kusama-rpc.polkadot.io",
                    "wss://kusama.api.onfinality.io/public-ws",
                    "wss://kusama-rpc.dwellir.com",
                    "wss://kusama.public.curie.radiumblock.xyz/ws",
                  ],
                },

              }